# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://janneogalex.no
title: Janne og Alexander
email: your-email@domain.com
author: Alexander Vedeler
description: Vi gifter oss 10.09.2022!

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
